# Generated by Django 3.1.7 on 2021-03-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210307_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='register_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
